module:
  package: "crud"
  author: "Chasing1020"
  email: "chasing1020@gmail.com"
  mysql:
    dsn: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
    max_idle_conn: 10
    max_open_conn: 20
    conn_max_idle_time: 2s
    conn_max_life_time: 2s

  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    max_retries: 3
    read_timeout: 1s
    write_timeout: 1s

schema:
  tables:
    - name: "course"
      columns:
        - name: "course_id"
          type: "string"
        - name: "name"
          type: "string"
        - name: "credit"
          type: "int"
        - name: "time"
          type: "int"
        - name: "department_id"
          type: "string"

    - name: "course_outline"
      columns:
        - name: "term"
          type: "string"
        - name: "course_id"
          type: "string"
        - name: "teacher_id"
          type: "string"
        - name: "class_schedule"
          type: "string"

    - name: "department"
      columns:
        - name: "department_id"
          type: "string"
        - name: "name"
          type: "string"
        - name: "address"
          type: "string"
        - name: "phone"
          type: "string"

    - name: "elective"
      columns:
        - name: "student_id"
          type: "string"
        - name: "term"
          type: "string"
        - name: "course_id"
          type: "string"
        - name: "teacher_id"
          type: "string"
        - name: "score"
          type: "string"

    - name: "student"
      columns:
        - name: "student_id"
          type: "string"
        - name: "password"
          type: "string"
        - name: "name"
          type: "string"
        - name: "sex"
          type: "string"
        - name: "birthday"
          type: "*time.Time"
        - name: "hometown"
          type: "string"
        - name: "phone"
          type: "string"
        - name: "department_id"
          type: "string"

    - name: "teacher"
      columns:
        - name: "teacher_id"
          type: "string"
        - name: "name"
          type: "string"
        - name: "sex"
          type: "string"
        - name: "department_id"
          type: "string"