definitions:
  model.Resp:
    properties:
      data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact: {}
paths:
  /user/:
    get:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Query User
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Resp'
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Create User
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Resp'
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update User
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Resp'
  /user/delete:
    delete:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Delete User
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Resp'
swagger: "2.0"
